### ISSUE TITLE
Dynamic Song Recommendation Based on Emotion Intensity

### ISSUE THREAD

**Issue by JOSEPHVIJAYRAJ** [SaiKiranReddyK28/Emotion-based-music-recommendation-system#24]
- Sai Divya can define the requirements for varying song recommendations based on emotion intensity.
- Vineeth can implement the necessary changes in the recommendation logic to reflect different levels of emotional intensity.

**Comment by Vineeth1810** [comment]
i have checked the code and according to our updated code, it gives songs based on intensity
