### ISSUE TITLE
Implement Emotion Detection UI Updates and Add Accessibility Features

### ISSUE THREAD

**Issue by SaiDivyaAdapa** [SaiKiranReddyK28/Emotion-based-music-recommendation-system#37]
- Develop the new UI for emotion detection with icons and real-time updates.
- Implement high contrast mode.

**Comment by SaiKiranReddyK28** [comment]
first i will try integrating Voice prompts.

**Comment by SaiKiranReddyK28** [comment]
i think voice prompts are unnecessary for this

**Comment by SaiKiranReddyK28** [comment]
Developed the new UI for emotion detection with icons and real-time updates.
Implemented high contrast mode
