### ISSUE TITLE
Support Playlist Enhancements and Customizable UI Themes

### ISSUE THREAD

**Issue by SaiDivyaAdapa** [SaiKiranReddyK28/Emotion-based-music-recommendation-system#39]
- Fetching album art and song metadata for the playlist.
- Implement the functionality for theme switching, ensuring compatibility across all UI elements.

**Comment by Abrarb702** [comment]
i think we can add another file for backend functionality.

**Comment by Abrarb702** [comment]
using Streamlit had access to different customizable themes, so no need for backend another file.
implemented fetching album art and song metadata for the playlist.
