### ISSUE TITLE
Model Improvement (CNN Training)

### ISSUE THREAD

**Issue by SaiKiranReddyK28** [SaiKiranReddyK28/Emotion-based-music-recommendation-system#4]
Task: Fine-tune the existing CNN model to detect a wider range of emotions with greater accuracy.
Dependencies: Dataset preparation, GPU availability for faster training.
Notes: Implement data augmentation to boost model performance.

**Comment by Vineeth1810** [comment]
started working on fine tuning

**Comment by Abrarb702** [comment]
dine with the fine-tuning and augmentation. ImageDataGenerator class is used to augment the dataset, allowing for better generalization.
